version: "3"

services:
  db:
    image: mysql:latest
    container_name: db_${ENV}
    environment:
      MYSQL_ROOT_PASSWORD: training-2023
      MYSQL_DATABASE: users
      MYSQL_USER: training
      MYSQL_PASSWORD: training_pw
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network-${ENV}

  app:
    image: hungpv1195/demo-build:{tag}
    build:
      context: nodejs/.
      dockerfile: Dockerfile
    container_name: app_${ENV}
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DB_HOST: db
      DB_USER: training
      DB_PASSWORD: training_pw
      DB_DATABASE: users
    networks:
      - app-network-${ENV}

networks:
  app-network-dev:
    external: true
  app-network-prod:
    external: true
