apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: api
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: hungpv1195/demo-build:{tag}
          command: ["npm", "start"]
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            exec:
              command:
                - "true"
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 15
